### ISSUE TITLE
Ограничение оповещений по времени

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#10]
Пользователь задает периоды времени, когда события (не) должны приходить, делать звуковое оповещение.
Надо продумать, как лучше реализовать.

**Comment by elagin** [comment]
Я пока не сильно разбирался как работет обмен данными. Новый инцидент пользователь создает через POST запрос, а приходят чужие инциденты и обновления по ним через пуши?

Тогда в период тихого часа надо новые инциденты помечать скрытыми, а после его окончания делать их видимыми.

**Comment by rjhdby** [comment]
Вроде как никем не востребованно
