### ISSUE TITLE
При первом старте после обновления должно вылезать окошко со списком доработок

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#104]

**Comment by elagin** [comment]
Этот же текст должен быть в   about

**Comment by rjhdby** [comment]
e512117f93fd475e8c441c8943f8526ee9432541
Добавил в Startup.onCreate вызов checkVersion
Оттуда можно будет вызывать всякие проверки

**Comment by rjhdby** [comment]
38074ebec665dad8de5d74da4d32b02e04b8281e
