### ISSUE TITLE
Нет возврата в инцидент после карты

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#106]
Например: выбираем инцидент. Жмем "на карту" (кстати, почему не "карта"?) открывается карта. Обратно в инцидент вернуться не возможно.

**Comment by rjhdby** [comment]
Займусь.
По хардварной кнопке back

**Comment by rjhdby** [comment]
5bc0e73cf7898116b81cac44a7dc6fba562a4755

**Comment by rjhdby** [comment]
Пока не закрыто полностью. Забыл про settings fragment
