### ISSUE TITLE
Открывается прошлый инцидент.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#107]
Пока тестировал переход с инцидента на карту обнаружил, что если после карты переходить обратно в список и тапнуть на другой инцидент, то открываются подробности того, что был выбран в прошлый раз.

**Comment by rjhdby** [comment]
Исправлено тут
https://github.com/rjhdby/motocitizen/issues/105

**Comment by elagin** [comment]
К сожалению воспроизводиться.
Выбираю инцидент, из него ухожу в на карту, там жму "события". Выбираю другой инцидент, а открывается предыдущий.

**Comment by rjhdby** [comment]
Все еще воспроизводится?

**Comment by elagin** [comment]
Да.
Открываю "первый" инцидент, в нем "перейти на карту". В главный экран. Тыкаю там второй инцидент и открывается первый.

**Comment by elagin** [comment]
Там еще смешнее. Если в п.4 написать сообщение, то оно не появиться в списке, но когда все-таки зайти во второй инцидент, то оно окажется там.

**Comment by elagin** [comment]
Активити-то убивать надо при выходе из него.
