### ISSUE TITLE
Не всплывает баллон на google map

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#108]
Выбираю инцидент. Подробности. На карту. Жму на иконку - всплывает баллон. После того как он закрывается, повторно больше не всплывает.

**Comment by rjhdby** [comment]
А тут можно мержить проблемы в одну?
Это идет паровозом к переходу с карты в детали по повторному клику

**Comment by elagin** [comment]
Вертятно да. Я со стороны тестера написал :)

**Comment by rjhdby** [comment]
Закрывай. Решено в 3265a1e01037fed9e9101feeb0ade6ea318805ed
