### ISSUE TITLE
Рефакторинг сообщений.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#110]
Перенос в listAdapter

**Comment by rjhdby** [comment]
?

**Comment by elagin** [comment]
Списки должны так работать: https://github.com/elagin/motocitizen/blob/messageScreen/Motocitizen/src/motocitizen/messages/MessageListAdapter.java
(на внешний вид окна пока не обращай внимания).

**Comment by elagin** [comment]
Тогда и элемент списка отдельным xml описывается это удобнее чем
public TableRow createRow(Context context)

**Comment by elagin** [comment]
Что-то забыл я, кажется у тебя были какие-то возражения по этому поводу?

**Comment by rjhdby** [comment]
Так тормознее получается

**Comment by elagin** [comment]
Конечно, по два раза элементы в мапе искать :) https://github.com/rjhdby/motocitizen/pull/310

**Comment by rjhdby** [comment]
Множественный инфлат xml-лек не факт, что лучше

**Comment by rjhdby** [comment]
Факт, лучше.
17ed970fad524a6cf5c5aba1eef9b2eb60bbe091
548b0df0ab3aa0b072ccc21163cc661be4dfa3ed
