### ISSUE TITLE
Дизайн Подробности инцидента

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#111]
Мы хотели объеденить "мотограждане" и "история" в один список.
Начитавшись про ActionBar, Tab, фрагменты и т.д. подумал, что сначала нужно сделать два фрагмента "сообщения" и "история". А переключать их можно будет по свайпу или табами как окажется лучше.

**Comment by rjhdby** [comment]
Не, мотограждане и историю объединять не надо. Первое показывает кто на месте/едет(при принятии решения, выезжать ли самому), а второе - общий лог всего, что творилось.

**Comment by elagin** [comment]
Для чего нужна история? Кто / когда создал видно в описании. Кто - когда выехал в "едут/на месте". Что там еще может быть? Когда его скрыли, отметили, кого забанили?

**Comment by elagin** [comment]
Пока вынесу сообщения, поехали и историю по отдельным фрагментам, хуже точно не будет.

**Comment by elagin** [comment]
Удалось вынести сообщения, но пока проблемы с отображением свежие написанного сообщения.

**Comment by rjhdby** [comment]
>Для чего нужна история? Кто / когда создал видно в описании. Кто - когда выехал в "едут/на месте". Что там еще может быть? Когда его скрыли, отметили, кого забанили?

Одним из главных принципов по изначальной задумки приложения была максимальная открытость.
Туда же в историю пойдет, кто и когда дал отбой, перенес точку, изменил адрес и описание. Что-бы любой пользователь мог спросить с модератора за любое действие.

**Comment by elagin** [comment]
Т.е. в Мотограждане должны быть только "уехал/приехал"? Тогда просто не нужно из "Мотограждан" копировать строки в "историю".

**Comment by rjhdby** [comment]
В мотогражданах должно быть "В пути" и "На месте"
В истории "Выехал, время", приехал, время" и "уехал, время"
