### ISSUE TITLE
Звонок контактному лицу.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#114]
Добавить возможность ввода телефонного номера контактного лица либо автоматического определения номера в тексте для осуществления звонка.

**Comment by rjhdby** [comment]
Только сегодня с Зайцем обсуждали.
Учитывая, что номер телефона програмными средствами не вытаскивается и в принципе является личной информацией есть два подхода, дополняющие друг друга
1) В настройках сделать поле, в котором можно указать свой телефон и использовать эту инфу интерактивно(через контекстное меню добавить в сообщение, сделать галку "разрешить звонки" и т.д.)
2) Сделать возможность послать личный пуш  с текстом "Перезвоните пожалуйста но поводу ДТП на номер +7блабла (Z@y)"

**Comment by elagin** [comment]
Причем тут личная информация не понятно, составивший инцидент публикует телефонный номер. Если ты имел ввиду "персональные данные", то просто номер телефона ими все равно не является.

Как это не вытаскивается? Парсишь текст, пытаешься найти номер. (11 цифр, могут быть разделены минусами, скобками). И если нашел что-то похожее делаешь их линком по клику на который идет набор номера.

Но, конечно же удобнее сделать ввод номера отдельным полем.

Про личный пуш не понятно, автор инцидента может не являться контактным лицом, а дать контакт кого-то кто там находиться, но не имеет установленного приложения.

**Comment by rjhdby** [comment]
> Если ты имел ввиду "персональные данные", то просто номер телефона ими все равно не является.
Тут номер телефона будет привязан к местоположению и нику, а это уже персданные
>Как это не вытаскивается? Парсишь текст, пытаешься найти номер.
Это и сейчас уже сделано, если номер где-то в тексте есть. Создай сообщение/инцидент с номером телефона и по длинному тапу выскочит ссылка на звонок. Я имел в виду, что из кишок девайса(с симки) номер автоматом не вытаскивается.

**Comment by rjhdby** [comment]
Закрыто?

**Comment by elagin** [comment]
Этот да, но связан с https://github.com/rjhdby/motocitizen/issues/126
