### ISSUE TITLE
Сделать механизм "Поделиться" для событий и сообщений. "пЕРЕХОД В НАВИГАТОР" для карты и событий.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#117]

**Comment by rjhdby** [comment]
"Поделиться" для списка событий
19a5f6dddb14e85670824cf906c895e0fab17b9b

**Comment by rjhdby** [comment]
Переход к навигатору при длинном тапе на карту
64bda113362c31e961c4f37a0396876a51c161a2

**Comment by elagin** [comment]
А так же https://github.com/rjhdby/motocitizen/commit/227b2d77174f0b77d6c4c3cddecf30e9bd44dfb0
