### ISSUE TITLE
Помечать на карте события, по которым дан отбой

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#118]
Перечеркнутым кружочком например.
Или просто делать иконку серой.

**Comment by elagin** [comment]
Тогда уж серой, чтобы тип не менялся. Да и в настройки тогда уж добивить возможность вообще скрывать их.

**Comment by rjhdby** [comment]
согласен

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/issues/421
