### ISSUE TITLE
После перезапуска приложения сбрасывался статус onway и можно было повторно выехать на одно и то же событие

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#121]

**Comment by rjhdby** [comment]
1c64c08dd40c7e721249e873cde954675f08f04b

**Comment by elagin** [comment]
Немного поломалось из-за этого коммита: https://github.com/rjhdby/motocitizen/commit/1184961eaac994b435734edbf47c76c3ea382139
При создании активити prefs еще null

**Comment by rjhdby** [comment]
Насколько я понял исправлено?

**Comment by elagin** [comment]
Ага
