### ISSUE TITLE
Зачем в настройках меню?

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#123]

**Comment by rjhdby** [comment]
незачем

**Comment by rjhdby** [comment]
Закрыто?

**Comment by elagin** [comment]
Надо убрать и закрыть. Думаю, что если все-таки вынести настройки в FragmentActivity, то все встанет на свои места.

**Comment by elagin** [comment]
Готово: https://github.com/rjhdby/motocitizen/commit/79676e0f1eb5b54e52eb94b9eabf5509befbb8ff
