### ISSUE TITLE
Не верное распознование телефона когда присутствуют другие цифры.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#126]
Из:
Запчасти, Прокол задней камеры Тркнсальпа. Нужна камера 130х80R17. Пилот +79031795357 Семён.

Получается:
80177903179

**Comment by elagin** [comment]
Не, у меня с регулярками совсем плохо. А вот, кстати, еще пример:

Бензин, смоленский бульвар,17,8985 922 52 36 => 78985922523

**Comment by rjhdby** [comment]
Да, я утром сам заметил. Сегодня поправлю.

**Comment by rjhdby** [comment]
исправлено тут 0918346d60a61f33c297a431d6f5d25e49ba56b6

**Comment by rjhdby** [comment]
Закрывай

**Comment by elagin** [comment]
Ага. Пока ошибок нет. Спасибо.

**Comment by elagin** [comment]
+7 не всегда нужно добавлять, например, если юзер начал номер с "8".
В почте у тебя пример нераспаршенных номеров в одном из инцидентов.

**Comment by rjhdby** [comment]
Matcher matcher = Pattern.compile("[7|8][ \\(-]?[\\d]{3}[ \\)-]?[\\d]{3}[ -]?[\\d]{2}[ -]?[\\d]{2}[\\D]").matcher(in);
...
            out.add(matcher.group().replaceAll("[^0-9]", ""));

Данный регексп ищет строчку строчку, начинающуюся с 8 или 7, потом либо сразу следующая цифра, либо пробел, либо тире, либо скобка, далее 3 цифры, далее снова цифра/тире/пробел/скобка, две цифры, цифра/пробел/тире, две цифры, потом все что угодно кроме цифр. (итого 11 цифр разделенных обычным набором символов используемых для записи телефона)
Следующий удаляет из найденного все кроме цифр.

Далее phoneButtonRow удаляет первый символ строки(7 или 8) и добавляет стандартный префикс +7

**Comment by elagin** [comment]
Да, сделай, пожалуйста, чтобы contactNumbers сразу возвращал номер в международном формате.

**Comment by rjhdby** [comment]
116ebc864f4bf79fe85b18397dfea662e0ab7249

**Comment by elagin** [comment]
Замечательно.
