### ISSUE TITLE
Лишний MCPoint.isVisible() ?

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#131]
Я правильно понимаю, что раз уж в getlist передаются координаты и радиус, то на клиенте проверять уже не нужно?

**Comment by rjhdby** [comment]
На клиенте могут поменять конфигурацию, а точки уже подгружены.

**Comment by rjhdby** [comment]
Я вообще думаю, что имеет смысл вообще весь список передавать, а фильтровать уже на клиенте

**Comment by elagin** [comment]
А зачем? Кто-то может оказаться в плохой связи. Я наоборот думал присылать только то, что изменилось. Но тогда надо на серверной стороне помнить какому клиенту чего отдавалось, а какому нет, это конечно усложнит порядком, пока и так хватает задач.

**Comment by rjhdby** [comment]
Сейчас так и происходит. Но если вдруг был запрошен список, а потом пользователь поменял радиус оповещения, либо уехал и в зону видимости новые попадают - то надо запрашивать список по новой.
