### ISSUE TITLE
NullPointerException - getDefaultSharedPreferencesName

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#134]
Источник https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=PreferenceManager.java&tc=android.preference.PreferenceManager&tm=getDefaultSharedPreferencesName&nid&an&c&s=new_status_desc

**Comment by rjhdby** [comment]
3261f4ef0b13a6587a680407380847781682f478

**Comment by elagin** [comment]
Пока закроем.
