### ISSUE TITLE
NullPointerException - AccidentDetailsActivity.update

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#136]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=AccidentDetailsActivity.java&tc=motocitizen.Activity.AccidentDetailsActivity&tm=update&nid&an&c&s=new_status_desc

**Comment by elagin** [comment]
Может быть исправлена в очередной версии.

**Comment by elagin** [comment]
Опять воспроизводится: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=MCAccidents.java&tc=motocitizen.app.mc.MCAccidents&tm=toDetails&nid&an&c&s=new_status_desc

Говорят, что происходит при открытии через пуш.

**Comment by elagin** [comment]
При нажатии на элемент пуша Startup.onResume вызывается что-ли?

**Comment by elagin** [comment]
Так и происходит. Сам с собой разговариваю.

**Comment by elagin** [comment]
Как при нажатии на пуш открывается нужный инцидент, а не тот что был активный до него?

**Comment by elagin** [comment]
Если ID инцидента содержиться в пуше, а приложение этот инцидент еще не скачало, то currentPoint будет null?

**Comment by elagin** [comment]
Скорее для того, чтобы понять дело ли в том, что нет активного инцидента: https://github.com/rjhdby/motocitizen/pull/144

**Comment by rjhdby** [comment]
>Если ID инцидента содержиться в пуше, а приложение этот инцидент еще не скачало, то currentPoint будет null?

Поэтому я при пушинтенте вызывал MCAccidents.refresh(). Сейчас что-то найти не могу

**Comment by elagin** [comment]
В Startup.onResume сначала запрашивается список инцидентов, а потом уже currentPoint определяется. Так что вроде как при наличии связи все инциденты должны на клиенте присутствовать. Другое дело, что народ ругается, что при нажатии на пуш открывается последний активный инцидент, а не тот, что в пуше пришел. В самом пуше содержиться ID инцидента или мы просто самый свежий открываем?

**Comment by elagin** [comment]
Пуш это просто "ярлык", чтобы приложение активизировалось?

**Comment by rjhdby** [comment]
Сейчас займусь

**Comment by rjhdby** [comment]
Вроде закрыто отказом от currentPoint
