### ISSUE TITLE
NullPointerException - MCLocation.getBestFusionLocation

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#137]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=MCLocation.java&tc=motocitizen.app.mc.MCLocation&tm=getBestFusionLocation&nid&an&c&s=new_status_desc

**Comment by rjhdby** [comment]
Исправлено
https://github.com/rjhdby/motocitizen/commit/3261f4ef0b13a6587a680407380847781682f478
