### ISSUE TITLE
Падение при нахождении в фоне.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#140]
Проснулся, включил fi-wi, приложение упало (сборка из master)

**Comment by rjhdby** [comment]
Скорее всего вылетает по приходу пуша.

**Comment by elagin** [comment]
Интересно, сегодня несколько раз наблюдал это в течении дня, хотя приложение ни разу не перезапускал.

**Comment by rjhdby** [comment]
Скорее всего исправлено тут
f34c885a0a30d63bf9b298b25ae922e0e946b66e

**Comment by rjhdby** [comment]
Вангую, что исправлено уходом от MCLocation.current
Закрывай

**Comment by elagin** [comment]
Спасибо.
