### ISSUE TITLE
Дизайн окна "список инцидентов".

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#142]
В деле установки кнопок в ActionBar я вроде продвинулся. Так и хочется в списке инцидентов сделать так же.
Сделать скрываемой панельку с текущим адресом. Показывать ее, например при помощи нажатия икноки в ActionBar.
Перенести туда "трубку", "создать инцидент", "не беспокоить" (с индикацией режима).

**Comment by elagin** [comment]
Туда же анимированную иконку поставить "обновление данных".

**Comment by rjhdby** [comment]
иконку да, а трубку и создать надо снизу. 99.9% инцидентов создаются водителями, когда телефон в одной руке.

**Comment by elagin** [comment]
Адрес пользовователя можно так показывать: https://github.com/lorensiuswlt/NewQuickAction (по клику на иконку в ActionBar).
