### ISSUE TITLE
Запрет обновления инцидентов, когда на экране другое активити.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#143]
Несколько раз наблюдал ситуацию, когда находился в каком-то из окон, но наблюдал прогрессбар: "обновление инцидентов".

**Comment by elagin** [comment]
Происходит такое при уходе из настроек в авторизацию или звуки и обратно в настройки.
При этом вызывается Startup.onResume, потому что настройки являются фрагментом Startup.
Хотел сделать проверку видно ли сейчас фрагмент main_screen:
```
Startup.onResume() {
//.....
        Fragment mainFragment = ((Activity) context).getFragmentManager().findFragmentByTag("main_screen");
        if(mainFragment.isVisible()) {
            if (isOnline()) {
                JsonRequest request = MCAccidents.getLoadPointsRequest();
```
Это работает, но оказалось, что при старте приложения на момент вызова onResume этот фрагмент еще не виден.

Какие есть идеи?

**Comment by rjhdby** [comment]
А как загрузка инцидентов связана с видимостью фрагмента?

**Comment by elagin** [comment]
Надо сделать если main не виден, то и загрузку инцидентов не делать, или хотя бы прогрессбар не рисовать. А с другой стороны если прогрессбар не рисовать и пока инциденты не докачались, а мы уже в main перешли тоже как-то кривовато получиться.

**Comment by elagin** [comment]
Это по гайдлайну PreferenceFragment должен содержаться в одном активити с главным? Может быть его оставить фрагментом, но в отдельное активити вынести?

**Comment by rjhdby** [comment]
Так, задача выпустить stable.
А так не против.

**Comment by elagin** [comment]
Решено https://github.com/rjhdby/motocitizen/pull/179
