### ISSUE TITLE
Получение лога

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#146]
Есть стандартный логгер Log можно его в файл направлять? Тогда можно присылать нам на почту, например. Тогда можно в критичных местах больше информации получать при падении.

**Comment by rjhdby** [comment]
Каким образом отсылку осуществлять?

**Comment by elagin** [comment]
Например: http://habrahabr.ru/post/112450/ Добавляя туда информацию по девайсу.

**Comment by elagin** [comment]
Вероятно связан с https://github.com/rjhdby/motocitizen/issues/203
