### ISSUE TITLE
NullPointerException - MCPoint.getDistanceFromUser

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#149]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=MCPoint.java&tc=motocitizen.app.mc.MCPoint&tm=getDistanceFromUser&nid&an&c&s=new_status_desc

**Comment by elagin** [comment]
Попытка исправить: https://github.com/rjhdby/motocitizen/pull/150

**Comment by rjhdby** [comment]
Похоже что решено

**Comment by elagin** [comment]
Хорошо, в крайнем случае переоткроем.
