### ISSUE TITLE
Разобраться, почему кидает в неправильные детали 

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#153]

**Comment by rjhdby** [comment]
А кидает в них потому, что у нас getlist работает асинхронно. Не успевает подтянуться точка.
Буду думать.

**Comment by elagin** [comment]
У нас как-то отдельно MCPoints и accListContent существуют. Обычно все через ArrayAdapter делают. Тогда легче синхронизировать все это. Здесь: https://github.com/elagin/GiveMeSpace стараюсь этого поддерживаться.

**Comment by rjhdby** [comment]
Сейчас делаю, чтоб по пушу приходил инцидент полностью, чтоб сразу в список вносить, без запроса

**Comment by rjhdby** [comment]
6db7905254e59e2600bcdd9e905c355c0ed3f678
