### ISSUE TITLE
Проверка полей в настройках

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#16]
Например если пользователь не указал ни одного типа инцидентов.

**Comment by rjhdby** [comment]
Значит ничего не хочет видеть. Бывает.

**Comment by elagin** [comment]
А как он тогда будет приложением пользоваться?

**Comment by rjhdby** [comment]
Для создания событий.

Ну и в будущем предполагается добавить информационные вкладки.
1) Порядок действия на дтп
2) эвакуаторы
3) ближайшие заправки/запчасти
4) подсказки по первой неотложной (?)
и т.д.

**Comment by elagin** [comment]
Т.е. не зная, что инцидент уже присутствувует в системе создать новый?

**Comment by rjhdby** [comment]
Ну тут основное ниже первой строки. :)

Конечно это оспариваемо, но мне кажется, что в открытом ПО имеет смысл и с пользователем открыто общаться. Снял все галки - ну значит зачем то это ему надо. Его право.

**Comment by elagin** [comment]
Если просто уведомить через Toast, то хуже не будет.

**Comment by rjhdby** [comment]
Согласен

**Comment by rjhdby** [comment]
ff372005e7831840645ec2706b76bc7247bf7737
Закрывай
