### ISSUE TITLE
Рефакторинг алгоритма запуска приложения.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#163]
Сначала создавать SplashActivity, в первую очередь должен нарисоваться, а потом производить первичную инициализацию с выводом результатов в список, например:
Авторизация...
registerGCM...
Определение местоположения...
Получение списка инцидентов...

После чего запускать Startup.
Таким образом получиться быстрее что-то показать юзеру, а потом уже спокойно готовиться к работе.

**Comment by rjhdby** [comment]
Не понял. Надо на пальцах объяснить

**Comment by elagin** [comment]
У нас сейчас первое активити Startup, пока оно запускается и много чего загружается мы видим черный экран и мигание нескольких "обмен данными".
Я предлагаю первым запускать новое актвити, которое сразу отобразиться, а потом начется процесс инициализации приложения, попытка авторизации, подписка на пуши и т. д. Когда все будет готово, оно закрывается и запускается Startup, которое уже пора в Main переименовать.

Практически во всех приложениях как мобильных, так обычных которые долго запускаются, на старте отображается небольшое окно.

**Comment by elagin** [comment]
Опять же если нужна авторизация, то сначала нужно AuthActivity вызвать, а уже потом Startup.

**Comment by rjhdby** [comment]
Давай отложим на вторую версию. Если сейчас начнем глобально переделывать, снова закопаемся в ошибках на неделю-две

**Comment by elagin** [comment]
Конечно. Жалко, что метки Future нет, как раз бы пригодилось.

**Comment by elagin** [comment]
Связано с https://github.com/rjhdby/motocitizen/issues/219

**Comment by elagin** [comment]
А так же с https://github.com/rjhdby/motocitizen/issues/37
