### ISSUE TITLE
Не обновляется история

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#164]
При скрыл/открыл, отбой/прибой не обновляется история.

**Comment by elagin** [comment]
Потому, что эти запросы не завернуты в HttpClient и вызываются из MCPopupWindow. Надо активити внутрь передавать.

**Comment by elagin** [comment]
Не удается в MCAccListPopup передать активити. Может быть разобрать этот класс и разнести по соответствующим активити?

**Comment by rjhdby** [comment]
Поркуа? Завтра гляну

**Comment by elagin** [comment]
По-прежнему актуально.

**Comment by elagin** [comment]
Первый этап: https://github.com/rjhdby/motocitizen/issues/209
