### ISSUE TITLE
Рисование окружности в ОСМ.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#168]
Нашел в одном из примеров: https://github.com/rjhdby/motocitizen/blob/7519bf56b676748bdf9df61628ce48c18dce2a04/Motocitizen/src/motocitizen/maps/osm/MCOSMMap.java
Но пока не нашел как этот org.osmdroid.bonuspack прикрутить, да может его и нету давно там.

Подскажи, пожалуйста.

**Comment by rjhdby** [comment]
Посмотри как сделано рисование окружности в гуглокартах в создании инцидента, суть та-же абсолютно. Наверное даже можно тупо этот оверлей скопировать в OSM

**Comment by elagin** [comment]
Там все проще, они давно все придумали: https://code.google.com/p/osmdroid/wiki/HowToUseGoogleWrapper

**Comment by rjhdby** [comment]
Ну в принципе оно и есть.
Только есть нюанс, mylocation рисует только текущую точку с радиусом погрешности определения. В случае, если вводить уточнение адреса на километр - придется отдельный оверлей рисовать.

**Comment by rjhdby** [comment]
Не актуально
