### ISSUE TITLE
Binary XML file line #2: Duplicate id 0x7f0b0074, tag null, or parent id 0x7f0b007c with another fragment for com.google.android.gms.maps.MapFragment

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#171]
https://play.google.com/apps/publish/?dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.IllegalArgumentException&tf=Activity.java&tc=android.app.Activity&tm=onCreateView&nid&an&c&s=new_status_desc

**Comment by elagin** [comment]
Не осилил я GoogleWrapper прикрутить. М.б. вообще пока OSM сделать не доступным?

**Comment by rjhdby** [comment]
Не актуально
