### ISSUE TITLE
Добавить в меню деталей пункт дублирующий скрытие подробностей

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#172]

**Comment by elagin** [comment]
Какой смысл дублировать? Что бы у Зайца эта функция работала?

**Comment by rjhdby** [comment]
Я уже много раз писал про специфику использования. Очень редко приложение используют сидя в удобном кресле, чаще всего это либо за рулем авто, либо на минутной мота остановке на обочине.
Контекст прост - одна правая рука.
Ну и потом, что плохого в дублировании функционала? Я понимаю, если бы интерфейс был мега перегружен, но в деталях у нас меню вообще не задействовано.

**Comment by elagin** [comment]
Да я все ни как не могу понять зачем одной рукой что-то делать в телефоне, когда есть две руки? Чтобы держать телефон в одной, а тыкать другой совсем не обязательно перчатку вторую снимать. У меня телефон 4,7 дюйма. Чёрта с два одной рукой им пользоваться получается.
В деталях, да, меню не загружено. Это только обычно не дублируется в меню то, что есть в экшинбаре.

В главном экране тоже надо аэшинбар приделывать, а ты говоришь, что трубку и создание инцидента надо внизу оставить. Две панели одновременно на экране держать будем и в меню продублируем? :)

**Comment by rjhdby** [comment]
Скажем так - это паттерн поведения целевой аудитории, выведенный в результате наблюдения в течении нескольких сезонов. Ну вот используют его так люди и все тут. Лично для тебя оно не нужно, а, например, лично для меня нужно.
Я в сезон довольно много катаюсь по дтп и если приходит пуш, либо надо уточнить адрес, либо быстро дать комментарий - останавливаешся на обочине, снимаешь опарую перчатку и по быстрому делаешь все манипуляции одной рукой - удобно.
Пару раз создавал событие за рулем авто, когда мимо ДТП по мкадовской пробке пробираешся - то же самое. Остановиться нельзя, скорость минимальна, но одной рукой руль все равно контролировать надо.

**Comment by rjhdby** [comment]
Что плохого в том, что у пользователя будет выбор, как именно ему сделать то или иное действие? К чему такая экономия?
Ради интереса можно вставить модуль статистики и посчитать, какую из кнопок будут нажимать чаще.

**Comment by elagin** [comment]
По статистике - верхнюю, потому, что ее видно, а про в меню мало кто догадается :)

**Comment by elagin** [comment]
Готово?
