### ISSUE TITLE
Сэкономим место в деталях инцидента?

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#175]
Таблица в два столбца, это, конечно же хорошо, но:
**Имя автора** как правило не много символов, **начало** всегда 5, **статус** тоже не очень длинный. Может быть их как-то плотнее расположить?
Например **сообщил**, **начало**, **статус** в одну строчку выписать:

Время / автор выровнять налево, а статус направо.
18:23 Z@Y........................ Активно.

**Comment by rjhdby** [comment]
Можно

**Comment by elagin** [comment]
Решено здесь: https://github.com/rjhdby/motocitizen/commit/52a098fbe81165c7ccf88f62bb34e6d1b8c173d5
Но переодически статус инцидента выпадает за край. Понять почему пока не удалось.
