### ISSUE TITLE
Работа с картой.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#18]
1. По клику на иконке инцидента отображать баллон с подробной информацией.
2. По клику внутри баллона переходить на окно с подробной информацией по этому инциденту.

**Comment by rjhdby** [comment]
Сейчас при повторном клике на иконку переходит в событие. Закрыто?

**Comment by elagin** [comment]
Переходит, но по поводу повторного клика как-то само по себе не очевидно.
Раз уж по первому клику открывается баллон, то по второму он должен закрываться :) М.б. стоит сделать переход по дабл-клику или кнопку в баллон вставить (хотя баллон мелкий всплывает).

**Comment by rjhdby** [comment]
К сожалению там метода на даблклик нет, только OnMarkerClickListener.
