### ISSUE TITLE
Фильтр текста.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#181]
Предлагаю на стороне сервера отрезать (при сохранении) в начале и конце лишние символы (пробелы, переводы строк) для сообщений, описаний инцидентов и т.д.

**Comment by rjhdby** [comment]
Да вроде trim стоит, завтра посмотрю на всякий

**Comment by elagin** [comment]
Во вчерашних сообщениях \n точно был.

**Comment by elagin** [comment]
Заодно сделать чтобы не сохранялось после чистки, например, пустое сообщение.

**Comment by rjhdby** [comment]
Контроль пустого делал, не должно дават ьотправить(я про сообщения)

**Comment by elagin** [comment]
Сервер ERROR отдает в этом случае?

**Comment by rjhdby** [comment]
Клавиша "Отправить" должна быть disabled, если сообщение не содержит видимых символов

**Comment by elagin** [comment]
Ни когда не был силён в регэкспах :(
