### ISSUE TITLE
Сервер: ошибка при создании инцидента "поломка", "угон", "ДТП".

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#197]
Успешно отрабатывает только "Прочее".
Инцидены создаюься, но в ответ приходит не по протоколу, поэтому юзеру отображается "ошибка" и инцидент можно создать еще раз.

push send{"result":19452}<br /><b>Warning</b>:  require_once(../../motocitizen.info/forum/ips_kernel/classEmail.php): failed to open stream: Нет такого файла или каталога in <b>/var/www/motocitizen/data/www/motocitizen.info/forum/qqadminchmod/sources/base/core.php</b> on line <b>1151</b><br /><br /><b>Fatal error</b>:  require_once(): Failed opening required '../../motocitizen.info/forum/ips_kernel/classEmail.php' (include_path='/var/www/motocitizen/data/www/motocitizen.info/forum/ips_kernel/HTMLPurifier:.:/usr/share/php:/usr/share/pear:../../motocitizen.info/forum/ips_kernel/') in <b>/var/www/motocitizen/data/www/motocitizen.info/forum/qqadminchmod/sources/base/core.php</b> on line <b>1151</b><br />

**Comment by rjhdby** [comment]
Ошибка уйдет, когда перейдем на новые сервера. АПИ форума гадит

**Comment by elagin** [comment]
А отфильтровать что-ли не ни как нельзя? Когда переезд?

**Comment by rjhdby** [comment]
Он в STDERR валит, не фильтруется. Только если на уровне хостинга отключать. До вторника
