### ISSUE TITLE
Блокировка засыпания устройства.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#2]
Не удобно отлаживаться когда оно все время засыпает.
Код есть, сделаю сам.

**Comment by elagin** [comment]
Проба здесь: https://github.com/elagin/motocitizen/tree/no_sleep но, кажется при выходе из приложения устройство перестает засыпать. Надо поисследовать, возможно виновато блокировние OnDestroy.

**Comment by rjhdby** [comment]
Еще актуально?

**Comment by elagin** [comment]
ага, всего на 2-й раз вылетает уже :)

**Comment by elagin** [comment]
Мешанина какая-то. Причем тут падение при смене карт?
Блокировку засыпания я не тестировал, кажется она не работает.

**Comment by rjhdby** [comment]
Оно само сюда прилепилось. Я хз почему
