### ISSUE TITLE
Идентичность содержимого в списке инцидентов и деталях.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#207]
В списке у нас:
Тип (расстояние)
Адрес

В деталях:
Тип
(расстояние) адрес.

По смыслу **расстояние** относиться к **адресу**, но с другой стороны как правило **тип** содержит мало символов, а часто занимает **адрес** дает две строчки.

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/issues/421
