### ISSUE TITLE
Результат createAcc

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#214]
Пардон, я не внимательно читал описание функции createAcc. Я имел ввиду, что если инцидент успешно создан, то надо возвращать ID='идентификатор' (ID = 2332), а в случае создания "прочего" инцидента возвращать ID=0.

**Comment by rjhdby** [comment]
Сейчас так и есть, не?

**Comment by elagin** [comment]
Сейчас просто "0" приходит.,

**Comment by rjhdby** [comment]
04-30 15:02:38.853  23689-23893/motocitizen.main D/POST﹕ http://forum.moto.msk.ru/mobile/main_mc_acc_json.php?med=mc_m_na&lon=37.6503991&calledMethod=createAcc&address=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%D0%9A%D0%B0%D0%BB%D0%B0%D0%BD%D1%87%D1%91%D0%B2%D1%81%D0%BA%D0%B0%D1%8F+%D1%83%D0%BB%D0%B8%D1%86%D0%B0%2C27&created=2015-04-30+15%3A02&status=acc_status_act&owner_id=8&login=rjhdby&descr=bbb&type=acc_o&lat=55.7746059
04-30 15:02:42.403  23689-23893/motocitizen.main D/JSON RESPONSE﹕ {"result":0}
04-30 15:03:09.803  23689-23897/motocitizen.main D/POST﹕ http://forum.moto.msk.ru/mobile/main_mc_acc_json.php?med=mc_m_na&lon=37.6503991&calledMethod=createAcc&address=%D0%9C%D0%BE%D1%81%D0%BA%D0%B2%D0%B0%2C%D0%9A%D0%B0%D0%BB%D0%B0%D0%BD%D1%87%D1%91%D0%B2%D1%81%D0%BA%D0%B0%D1%8F+%D1%83%D0%BB%D0%B8%D1%86%D0%B0%2C27&created=2015-04-30+15%3A02&status=acc_status_act&owner_id=8&login=rjhdby&descr=bbb&type=acc_b&lat=55.7746059
04-30 15:03:14.033  23689-23897/motocitizen.main D/JSON RESPONSE﹕ {"result":85}

**Comment by elagin** [comment]
Должно быть {"result": id=85}
Тогда код:
```
    public void parseResponse(JSONObject json) {
        if (json.has("result")) {
            String result = "error";
            try {
                result = json.getString("result");
                if (result.contains("ID")) {
                    Toast.makeText(this, this.getString(R.string.send_success), Toast.LENGTH_LONG).show();
                    finish();
                } else if (result.equals("READONLY")) {
                    Toast.makeText(this, this.getString(R.string.not_have_rights_error), Toast.LENGTH_LONG).show();
                } else if (result.equals("PROBABLY SPAM")) {
                    Toast.makeText(this, this.getString(R.string.too_often_acts), Toast.LENGTH_LONG).show();
                } else {
                    Toast.makeText(this, result, Toast.LENGTH_LONG).show();
                }
            } catch (JSONException e) {
                e.printStackTrace();
                Toast.makeText(this, this.getString(R.string.parce_error), Toast.LENGTH_LONG).show();
            }
        } else {
            Toast.makeText(this, this.getString(R.string.send_error), Toast.LENGTH_LONG).show();
        }
    }
```
сможет опеределить, что инцидент был успешно создан либо обработать все известные ему возвращаемые ошибки, а так же определить что пришел какой-то не стандартный ответ.

**Comment by rjhdby** [comment]
Да не вопрос. Только скорее вот так {"result": {"id":"85"}}

Если прям сейчас поменяю, ничего в коде приклада менять не придется?

**Comment by rjhdby** [comment]
Сделал

**Comment by elagin** [comment]
Да, я как раз под это и заточил уже.

**Comment by rjhdby** [comment]
Перед релизом надо будет поменять ID на id, в прикладе и на сервере. Для единообразности.

**Comment by elagin** [comment]
Спасибо, работает.
