### ISSUE TITLE
Обновление данных в AccidentDetailsActivity

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#217]
У нас сейчас при каждом чихе происходит вызов getlist, например после написания сообщения, нажатия кнопки "onway", "скрыть" / "отбой".
Считаю что это не очень правильно. Т.к. все равно перед переходом в главный экран эта функция опять будет вызвана.
Но внутри деталей нужно отслеживать изменения в инциденте, поэтому надо предлагаю:
переименовать getlist в getAccidents, добавив входной параметр id - идентификатор инцидента.
Таким образом, если в запросе содержиться id, то возвращается массив с одним элементом.

**Comment by rjhdby** [comment]
А смысл? Самые большие накладные расходы - установка соединения. А после установки прислать 100байт или 300 - никакой разницы. Тем более, что если были изменения только по одному инциденту, то вернется только он один.

**Comment by elagin** [comment]
Так может быть вообще пушем обновлять тогда? Что будет если при попытке отправить пуш связи с клиентом не будет?
