### ISSUE TITLE
Извлечение контактных телефонов из переписки.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#218]

**Comment by elagin** [comment]
Кстати, да: https://github.com/rjhdby/motocitizen/issues/218

**Comment by rjhdby** [comment]
Вроде же всё пучком давно

**Comment by elagin** [comment]
Из сообщений я не делал еще.

**Comment by rjhdby** [comment]
Из сообщений извлекаются в контекстное меню самого сообщения. Имхо так правильней, потому как если разные телефоны в разных сообщениях, то в общем списке можно запутаться, а так конкретный номер по конкретному сообщению.

**Comment by elagin** [comment]
Хорошо.
