### ISSUE TITLE
Переходы Список инцидентов <=> Карта.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#221]
По мотивам  https://github.com/rjhdby/motocitizen/issues/107 и https://github.com/rjhdby/motocitizen/issues/106
Есть у нас некоторая путаница в том числе и с кнопкой назад. Если мы вдруг оказались после карты в списке, то по кнопке "назад" не нужно обратно переходить в карту, потому, что список условно считается корневым элементом.

**Comment by rjhdby** [comment]
Сделал выход из приложения по нажатию кнопки назад, если текущий экран  - экран со списком.
