### ISSUE TITLE
Статусы инцидента.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#227]
Давай уже определимся. Если есть в меню "отбой", то и статус такой должен быть. Если статус "закрыт", то тогда такой пункт в меню должен быть.

Кстати, "скрытый" это какой-то плохой инцидент, который модераторы, например спамом или хулинанством посчитали?

**Comment by rjhdby** [comment]
Статусов три.
1) Активный. Тут понятно.
2) Отбой. Тут, думаю тоже.
3) Скрыт - плохой инцидент. Спам, хулиганство, дубль и т.д.

Другое дело, что имеет смысл еще и подстатусами оперировать, что бы было понимание, что был дан отбой, а потом его отменили. Но это уже гемор.

**Comment by elagin** [comment]
Был отбой и его отменили это в истории видно. А для использования важно, актуален он сейчас или нет.

Мой вопрос-то был в том, что у активного инцидента есть кнопка "отбой". При ее использвании появляется статус "завершено". Может быть тогда статус писать тоже "отбой". Тогда будет понятна кнопка "отменить отбой".

**Comment by rjhdby** [comment]
Теперь понял. Да конечно, сейчас поправлю.

**Comment by rjhdby** [comment]
626307f436c9a866d312a1d8826cff72a7dd7fe4
