### ISSUE TITLE
При старте не загружает события. Загружает только после ручного обновления.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#23]
03-29 14:00:19.081    1856-1856/motocitizen.main D/POST﹕ lon=37.62273406982422&distance=10&calledMethod=getlist&user=rjhdby&lat=55.752296447753906
03-29 14:00:19.281    1856-1856/motocitizen.main D/JSON ERROR﹕ 200
03-29 14:00:19.281    1856-1856/motocitizen.main D/JSON RESPONSE﹕ {"list":[{"error":"no_new"}]}

**Comment by elagin** [comment]
У меня не воспроизводится. По крайней мере после старта вижу инциденты не нажимая "обновить".

**Comment by elagin** [comment]
А, именно это я наблюдаю, но все равно сейчас вижу 3 инцидента за сегодня и один за вчера.
getlist что должна возвращать, новые сообщения со времени последнего запроса?

**Comment by rjhdby** [comment]
События в которых были какие либо изменения с момента последнего запроса. (создание, комментарий, список волонтеров)

**Comment by elagin** [comment]
Так это проблема на серверной стороне?

**Comment by rjhdby** [comment]
Скорее всего да, потому на себя и заассигнил
