### ISSUE TITLE
Многострочный ввод сообщения.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#235]
Сделать как в whatsup - добалять / убирать сторчку если текст перестает помещаться.

**Comment by elagin** [comment]
Для mc_new_message_text можно использовать android:inputType="textMultiLine".
Но когда в нем появляется больше, чем одна строка его верхняя часть проваливается под mc_det_messages_scroll.

Хотя, если сразу в xml-файле для mc_new_message_text установить две строки, то mc_det_messages_scroll правильно уменьшается.

**Comment by rjhdby** [comment]
Актуально?
