### ISSUE TITLE
При старте идет лишний запрос списка событий к серверу 

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#24]
03-29 14:00:19.081    1856-1856/motocitizen.main D/POST﹕ lon=37.62273406982422&distance=10&calledMethod=getlist&user=rjhdby&lat=55.752296447753906
03-29 14:00:19.281    1856-1856/motocitizen.main D/JSON ERROR﹕ 200
03-29 14:00:19.281    1856-1856/motocitizen.main D/JSON RESPONSE﹕ {"list":[{"error":"no_new"}]}
.........
03-29 14:00:19.911    1856-1856/motocitizen.main D/POST﹕ lon=37.62273406982422&distance=10&calledMethod=getlist&user=rjhdby&lat=55.752296447753906
03-29 14:00:20.021    1856-1856/motocitizen.main D/JSON ERROR﹕ 200
03-29 14:00:20.021    1856-1856/motocitizen.main D/JSON RESPONSE﹕ {"list":[{"error":"no_new"}]}

**Comment by elagin** [comment]
Надо вообще рефачить алгоритм запуска. Изначально создавалась куча статичных объектов (например обе карты). А это не всегда нужно.

**Comment by elagin** [comment]
Потому, что первый раз вызывается в Startup.onCreate -> конструктор MCAccidents
а второй в Startup.onResume -> MCAccidents.refresh(this);

Нужно выяснить можно ли обойтись без MCPoints.load() в конструкторе MCAccidents

**Comment by elagin** [comment]
Исправлено https://github.com/rjhdby/motocitizen/pull/28
