### ISSUE TITLE
При каждом заходе в детали обновляется геопозиция

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#240]

**Comment by elagin** [comment]
Чего в этом плохого? Мы вообще контролируем ли это, как я понял, мы регистриуем FusionLocationListener, а он как-то асинхронно вызывается. Или ты что-то другое имел ввиду?

**Comment by rjhdby** [comment]
Это меня проглючило. NETWORK провайдет скакал постоянно - от того и геопозиция запрашивалась
