### ISSUE TITLE
Куча "приехал" (серверная часть)

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#248]
Вчера был "ТЕСТ ПУШ" от Gratias. Так в истории огромное количество его "приехал".Думаю, что это произошло во первых из-за того, что он создал инцидет там где находился долгое время. А во втроых у нас нет проверки на то, что достаточно один раз "приехать". Если только не пришлось "приехать" в другое место, а потом вернуться.

**Comment by elagin** [comment]
В других инцидентах так же один и тот же приезжает по несколько раз.

**Comment by rjhdby** [comment]
8b1ad31ce728c51c09ca4e390fefb905b4c87288
