### ISSUE TITLE
Сломан индикатор "не беспокоить"

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#249]
У меня он включен. Выключаю, перезахожу - опять включен.

**Comment by rjhdby** [comment]
Надо его сохранять в преференсах и выставлять при запуске. Сейчас у нас он принудительно выставляется в "беспокоить"

Ну а вообще это правильно. Человек на ночь выключил, потом с утра телефон включил и ессно забы(и)л на включение обратно. Будет больше ора, если при запуске включаться не будет.

**Comment by elagin** [comment]
Откоментировал на форуме.
