### ISSUE TITLE
Отдельное окно для ввода описания инцидента.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#25]
Z@y жалуется, что на его маленьком телефоне клавиатура накрывает поле ввода.
Возможно стоит для этого сделать отдельное окно в визарде (без фрейма "что, где, когда").

**Comment by rjhdby** [comment]
В свое время придумал такое(но руки не дошли) - при фокусе на поле ввода(в создании инцидента и в сообщениях) анимировать верхний блок за пределы экрана

**Comment by elagin** [comment]
А обратно возвращать когда на клавиатуре "готово" нажали? Известно ли когда кнопка "готово", а когда "enter" отображается?

**Comment by rjhdby** [comment]
Привязать к скрытию клавиатуры.

**Comment by elagin** [comment]
Решено в виде кнопки для отображения / сокрытия верхней панели.
