### ISSUE TITLE
Сохранять историю прочитанных сообщений в инцедентах, что бы при открытии не помечались новыми

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#252]

**Comment by elagin** [comment]
Пора базу данных прикручивать?

**Comment by rjhdby** [comment]
Думаю хватит стринга с json'ом в пропертях

**Comment by elagin** [comment]
Касается https://github.com/rjhdby/motocitizen/issues/309

**Comment by elagin** [comment]
Решение https://github.com/rjhdby/motocitizen/pull/368

**Comment by elagin** [comment]
Наверное уже можно закрыть?

**Comment by rjhdby** [comment]
У меня не пашет почему то.

**Comment by elagin** [comment]
Нужно имено в загладку с сообщениями заглянуть.
