### ISSUE TITLE
Переделать индикацию идущего обновления событий.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#254]
Например в экшнбар вынести, либо тонкую линию с бегущей полоской. Что б не перекрывать основной экран при каждом чихе

**Comment by elagin** [comment]
Думал уже об этом. Может затронуть сетевой движок. Надо разобраться как анимацию делать.

**Comment by elagin** [comment]
Иконку в экшинбаре крутить научился.
А что должно происходить в момент обновления. Сейчас гуй блокируется.  Если будет индикатор в экшинбаре, то при обновлении информации юзер сможет уйти, например, в подробность инцидента, не отвалиться ли что-нибуди при этом?

**Comment by rjhdby** [comment]
Да не должно отвалиться.

**Comment by elagin** [comment]
Решено здесь: https://github.com/rjhdby/motocitizen/commit/d0f8aeecc266dee8906a3ef28790e7df340c39d8
