### ISSUE TITLE
Проблемы с GPS.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#256]
У нескольких человек в приложении не работает GPS. При этом в гуглокартах все ок.

Возможно решение в этом направлении
http://stackoverflow.com/questions/16764863/gps-not-working-in-my-application-but-works-in-google-maps

**Comment by elagin** [comment]
Сходил по ссылке. Там вообще не как у нас реализовано.

**Comment by rjhdby** [comment]
Да, там старая реализация, но возможно имеет смысл поиграться уровнем энергопотребления. Если долго не ловит спутник - принудительно переключать на вышки и вайфай
