### ISSUE TITLE
Куча пушей

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#257]
Если приложение не запущено какое-то время, то при старте наввливается куча пушей. Мне кажется в таком случае должен приходить один последний. Все равно перейдя в приложение можно все остальные инциденты посмотреть. Возможно ли как-то удалять пушки из очереди?

**Comment by rjhdby** [comment]
Я так вообще считаю, что надо только один пуш держать - последний, а 
остальные гасить.
Точно можно удалять, надо почитать доки.

С уважением, Андрей Громов.
т. 6210



От:     Pavel <notifications@github.com>
Кому:   agromov@alfabank.ru, 
Дата:   12.05.2015 11:03
Тема:   [motocitizen] Куча пушей (#257)
Отправитель:    <andrewgrom@rambler.ru>



Если приложение не запущено какое-то время, то при старте наввливается 
куча пушей. Мне кажется в таком случае должен приходить один последний. 
Все равно перейдя в приложение можно все остальные инциденты посмотреть. 
Возможно ли как-то удалять пушки из очереди?
?

**Comment by elagin** [comment]
А в какой момент они вообще формируются? Подписка на них происходит когда приложение запускается? Как тогда вообще очеред пушей получается? С момента подписки не может много инцидентов создаться. Соответсвенно пуши должны приходить только на те события, которые произошли после старта приложения.

А кажется я понял: приложение регистрируется на пуши и закрывается. Облако не знает, что приложение закрылось, а просто ставит их в очередь и когда подписываемся заново они все сваливаются. Значит при повторной регистрации надо очищать очередь для этого юзера.

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/issues/299
