### ISSUE TITLE
Отмена "Выехал"

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#267]
Бывает так, что человек нажал кнопку "выехал", подтвердил, но выехать не получилось. Нужно дать ему возможность снять этот флаг.

**Comment by rjhdby** [comment]
В серверном API реализовано
https://github.com/rjhdby/MobileServer/issues/3

**Comment by elagin** [comment]
Ждем https://github.com/rjhdby/motocitizen/issues/306

**Comment by elagin** [comment]
Тогда надо и в приложении вводить статус "onway_cancel"
