### ISSUE TITLE
CreateAccActivity - переход на enum

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#272]
Сейчас тип создаваемого инцидента храниться в мешанине  medText, globalText, med.
Нужно завести типы, переключать их в процессе создания. Выходные данные формировать при нажатии кнопки "готово".

**Comment by rjhdby** [comment]
Нужно сесть и нарисовать схему взаимодействия. Вообще, надо с тобой собраться и порисовать картинки и блоксхемы.

**Comment by elagin** [comment]
Так добро пожаловать :)

**Comment by rjhdby** [comment]
Завтра за тобой заеду и повезу в мотобар чаем поить и с целевой аудиторией знакомить

**Comment by elagin** [comment]
Где-то в 12:30 я буду свободен.
