### ISSUE TITLE
isInPlace - AccidentsGeneral.points.getPoint(accId) : null pointer exception

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#274]
Интересная наблюдается штука:
Запускаю приложение. При попытки любого инцидента получаю null pointer exception в
```
    private static boolean isInPlace(Location location, int accId) {
        double meters = AccidentsGeneral.points.getPoint(accId).getLocation().distanceTo(location);
        double limit = location.getAccuracy() * 2 + 1000;
        return meters < limit;
    }
```
Потому, что мой user_id = 23 почему-то попадает во accId, а такой записи в AccidentsGeneral.points конечно же нет.

Кусок ответа:
[{"action":"create_mc_acc","owner":"Азимут","id":"9334","uxtime":"1431732038","id_user":"23"},{"action":"inplace","owner":"Азимут","id":"9335","uxtime":"1431732059","id_user":"23"}]

**Comment by rjhdby** [comment]
актуально?

**Comment by elagin** [comment]
Пока нет.
