### ISSUE TITLE
Волонтерская работа.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#286]
Как я себе представляю функционал посещений:
В профиле юзера есть поля: int onway,  int inplace и история действий волонтера (время, событие, AccId).

Режим **Выезд**
Волонтер нажимает "выехал".
1) добавляем запись "onway" в истрорию действий волонтера.
2) попытаемся вызвать функцию api.onway.
3) отмечаем в профиле юзера onway=AccID.
Периодически FusionLocationListener дает нам новое местоположение и мы проверяем не приблизились ли мы на какоето расстояние к onway=AccID.
Если это так, то переходим в

Режим **На месте**
1) добавляем запись "onplace" в истрорию действий волонтера.
2) попытаемся вызвать api.onplace. 
3) отмечаем в профиле юзера inplace=AccID, onway=0
Начинаем отслеживать насколько волонтер удалился от места инцидента. Если он уехал:
1) добавляем запись "leave" в истрорию действий волонтера
2) попытаемся вызвать api.leave. 
2) отмечаем в профиле юзера inplace=0

При смене режимов сохранять историю действий волонтера в файл и при запуске приложения его загружать. После удачного вызова api.onplace, api.leave вероятно из истории нужно удалять отправленные записи.

**Comment by rjhdby** [comment]
Ну в общем то оно так и реализовано сейчас

**Comment by elagin** [comment]
Тогда бы не было ошибок, которые наблюдались и продолжнают наблюдаться.

**Comment by rjhdby** [comment]
Ты издеваешься? Каким образом ошибки в коде проецируются на целевой алгоритм?

**Comment by elagin** [comment]
В api нет функций которые я описал, истории волонтерской тоже нет. Поэтому и пытаемся установить "inplace" на инцидент которого нет в списке.

**Comment by elagin** [comment]
И ошибки в твоем алгоритме. Код-то правильный :)

**Comment by rjhdby** [comment]
вот оно
    case 'onway' :
        require_once 'class/onway.class.php';
        $onway = new onway ( $_POST );
        $result = array (
            "result" => $onway->onway ()
        );
        break;
    case 'inplace' :
        require_once 'class/onway.class.php';
        $onway = new onway ( $_POST );
        $result = array (
            "result" => $onway->inplace ()
        );
        break;
    case 'leave' :
        require_once 'class/onway.class.php';
        $onway = new onway ( $_POST );
        $result = array (
            "result" => $onway->leave ()
        );
        break;
    case 'cancelOnWay' :
        require_once 'class/onway.class.php';
        $onway = new onway ( $_POST );
        $result = array (
            "result" => $onway->cancel ()
        );
        break;
