### ISSUE TITLE
AccidentDetailsFragments.update - NullPointerException

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#288]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.NullPointerException&tf=AccidentDetailsFragments.java&tc=motocitizen.Activity.AccidentDetailsFragments&tm=update&nid&an&c&s=new_status_desc
```
    protected void update() {
        currentPoint = AccidentsGeneral.points.getPoint(accidentID);
    }
```
Думаю, что может возникать если пытаемся открыть инцидент в тот момент когда идет обновление инцидентов и этого инцидента в списке уже нет. Еще один камень в огород неблокируемого для пользователя обновления списка инцидентов.

Предполагаемое решение:
Выводить сообщение "Этот инцидент потерял актуальность" и возвращать обратно в список.

**Comment by rjhdby** [comment]
Самая длительная операция при обновлении - сеанс связи с сервером. До окончания этой операции локальный список жив. Мне кажется, что попасть ровно на момент парсинга ответа - это что-то из ненаучной фантастики.

**Comment by elagin** [comment]
Тем не менее ошибка прериодически встречатеся. Я немного порядок навел в последних коммитах, сейчас хотя бы кода меньше стало.

Еще у нас сейчас куча строк "AccidentsGeneral.points.getPoint(accidentID);" размазанно по всем деталям инцидентов. Надо это все причестать.

**Comment by elagin** [comment]
Кстати, если зайти в инцидент не модератору, и его потом кто-то закроет, то при нажатии "выехал" или написания сообщения ошибка скорее всего воспроизведется.

**Comment by elagin** [comment]
Вечером попробую сделать так, чтобы при getPoint(accidentID) == null выводился диалог "возможно диалог не актуален" и подробности инцидента закрывались.
