### ISSUE TITLE
Исчезает не дописанный инцидент.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#29]
Начинаем создавать новый инцидент. Сворачиваем приложение, возвращаем обратно и оказываемся на "главном" экране. Не дописанный инцидент исчезает.

Надеюсь исправить, т.к. как раз примерно в этом месте сейчас ведется рефакторинг.

**Comment by rjhdby** [comment]
Нюанс.
Создание инцидента - занятие достаточно редкое и по любому связанное с какими то форс-мажорными обстоятельствами. Если пользователь свернул приложение в момент написания, то скорее всего либо уже получил по нему пуш, либо решил, что наверное не стоит народ беспокоить. И когда при следующем запуске ему сразу форма создания вылезет - может на автомате нажать кнопку отправить.
С другой стороны, может быть свернул, что бы что-то уточнить/срочное сделать.
Наверное будет правильным сделать временнОе  ограничение, если прошло более 10 минут, то возвращать уже в главный экран.

PS Возврат на главный происходит из-за вызова MCAccidents.refresh в resume

**Comment by elagin** [comment]
Для начала переношу в отдельное активити. А то событие редкое, а об'ект все время в памяти. А перед отправкой вообще подтверждение спрашивать принято.

**Comment by rjhdby** [comment]
Закрыто?

**Comment by elagin** [comment]
Эээ трудно сказать. Сейчас если свернуть и развернуть, то отображается Startup, но при нажатии "создать инцидент" попадаю в недописанный.
Надо как-то определять, какое окно было активно при сворачивании и в него возвращаться.

**Comment by elagin** [comment]
>PS Возврат на главный происходит из-за вызова MCAccidents.refresh в resume
А почему на каком бы Активити не сворачивал приложение, при возврате обратно вызывается Startup.onResume, а не onResume того активити на котором было свернуто приложение?

**Comment by rjhdby** [comment]
хз

**Comment by elagin** [comment]
Может быть это как-то с получением пушей связано?

**Comment by rjhdby** [comment]
Скорее всего

**Comment by rjhdby** [comment]
Это связано с манифестом.
```
<activity
            android:name="motocitizen.Activity.MainScreenActivity"
            android:launchMode="singleInstance"
```
launchMode курить надо
