### ISSUE TITLE
Вернуться к gzip при общении с сервером

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#295]

**Comment by rjhdby** [comment]
Готово. Замержу позже оптом.

**Comment by rjhdby** [comment]
ca562d42e23619b5de8e8eb6c52ab98e0e93d0c5

Сделал автоопределение входящего потока. Принимает как с gzip, так и без него. На сервере gzip можно включать только после того, как все обычные пользователи обновятся

**Comment by elagin** [comment]
Если не актуально, то закрой.

**Comment by rjhdby** [comment]
Пока актуально.
