### ISSUE TITLE
Ограничить количество нотификейшенов в трее.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#299]
Достаточно держать последние 3-4

**Comment by elagin** [comment]
Не серверная ли это задача?

**Comment by rjhdby** [comment]
63f886c37e6c7778d20e3e7aeb87b99ce9fd0ee8

Поставил ограничение 4 последних.
Можно добавить в настройки.

MyPreferences.setMaxNotifications(int code)
тэг "notifications.max"

**Comment by elagin** [comment]
При переходе с нотификейшина нужно удалять остальные. Т.к. все свежее пользователь сможет в приложении увидеть.

**Comment by rjhdby** [comment]
Да, думал об этом. Сейчас сделаю

**Comment by rjhdby** [comment]
e898cc7e0b070f3066bbab21c0d047e3b4d2f20b

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/commits/master
