### ISSUE TITLE
Геопозиционирование. Переходить на NETWORK в фоне

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#3]
Сейчас при уходе в фон геопозиционирование выключается. Надо сделать что-бы работало, но в максимально энергосберегающем режиме

**Comment by elagin** [comment]
Можно подробнее, что такое "максимально энергосберегающий режим", это "NETWORK"? Зачем в фоне это нужно, если пользователь не видит приложение? Для "выехал" ?

**Comment by rjhdby** [comment]
Для определения кто на месте.
Когда на дтп приезжаешь, далеко не всегда вспоминаешь/есть время лезть в приложение чтоб отметиться приехавшим.

**Comment by elagin** [comment]
Тогда это и надо связать с нахождением на месте инцидента. Т.е. отследить что приехал и ходить в энергосбережение. Отследил, что покину - возвращаемся в обычный режим.

З.Ы. Что такое "NETWORK"?

**Comment by rjhdby** [comment]
Это из старой гугловской терминологии. GPS - координаты по спутникам, жрет батарею. NETWORK - примерное местоположение по базовым станциям.

**Comment by rjhdby** [comment]
Плотно займусь этим моментом

**Comment by rjhdby** [comment]
cc28dd8247c033133da60c03bf9eecb7abbefe0b
