### ISSUE TITLE
Установка "выехал" для скрытого инцидента.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#30]
Должна ли быть возможность "выехал" для скрытого инцидента? Мне это удалось для вчерашнего (угон, Леволинейная)

**Comment by rjhdby** [comment]
Вообще конечно нет.
Есть две ситуации, когда пользователь может нажать кнопку для скрытого:
1) Нажал в не обновленном списке.
2) Список обновлен, но он модератор или выше

Первое решать надо на стороне сервера, второе в приложении.

**Comment by rjhdby** [comment]
Проблема решится тут
https://github.com/rjhdby/motocitizen/issues/152
