### ISSUE TITLE
Разобраться с хардовой кнопкой back.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#301]

**Comment by elagin** [comment]
Можно конкретики? А то выглядит как "исправить ошибку в приложении".

**Comment by rjhdby** [comment]
Надо нарисовать диаграмму, откуда и куда эта кнопка должна перекидывать. Ну и сделать, чтоб она так именно и работала.

**Comment by elagin** [comment]
Путь перехода писать и по нему обратно идти, если переход не возможен (не актуальный инцидент), то перескакиваем через шаг.

**Comment by rjhdby** [comment]
Я так уже пробовал - фигня выходит. Проще и надежнее закодить маршруты в лоб
