### ISSUE TITLE
Редизайн Настроек.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#303]
Хочу предложить типы инцидентов в подраздел положить. Пусть в корне настроек будет:

Типы инцидентов
ДТП, Поломки (перечислено то, что включено)

При клике рисовать стопку чекбоксов.

**Comment by rjhdby** [comment]
Попробуй, посмотрим :)

**Comment by elagin** [comment]
Попробовал - все плохо. Имеет дождаться поддержки планшетов и сразу все сделать за один раз.

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/issues/421
