### ISSUE TITLE
Передавать в асинхронные запросы к серверу callback функцию, вместо захардкоденых действий

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#307]

**Comment by elagin** [comment]
Хозяйке на заметку: https://github.com/rjhdby/motocitizen/issues/238

**Comment by elagin** [comment]
Эээ так у нас сейчас так и работает:
```
    protected void onPostExecute(JSONObject result) {
        super.onPostExecute(result);
        super.dismiss();
        activity.parseOnwayResponse(result, currentId);
    }
```

**Comment by rjhdby** [comment]
Надеюсь ты не трогал ветку network сегодня. Я там напеределывал от души. :)

**Comment by elagin** [comment]
Нет, по твоим действиях в тикетах я понял что трогать не нужно.

**Comment by rjhdby** [comment]
e9c9ff147661e73ae7efe79f5cae82752f53db66
Остались мелкие косяки

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/issues/306

**Comment by rjhdby** [comment]
b1c8c6036936cc0e595abeba011fe75d3db06fbc
132c26a9b9e4c4019e97b3011143e736658563df
