### ISSUE TITLE
Окно "угон".

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#31]
Может быть стоит в будущем доработать окно угона, добавив там поля:
*Производитель
*Год выпуска
*Приметы
*Фото
и т.д.
Приозводитель - выпадающий список, можно будет статистику какую-то собирать.
Фото - мы "попадаем" на дисковое пространство. Но с другой стороны и так на форуме народ фото может публиковать.

**Comment by rjhdby** [comment]
По хорошему я бы вообще угон убрал из приложения, но оно исторически на мотогражданах отслеживается.
Можно рассматривать угон как отдельную функциональность, не связанную с основной и отсюда и плясать.
