### ISSUE TITLE
Нет слова "ДТП" в "Наезд на пешехода".

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#32]
При наборе этого инцидента изчезает слово "ДТП" в globalText.
Надеюсь исправить в последующем рефакторинге.

**Comment by rjhdby** [comment]
Экономии для. Событие крайне редкое и работают с ним не как с обычным ДТП.
Раскрою.
Одной из главных задач МГ изначально стояло выправление ситуации, когда мотоциклиста без вопросов признавали виновным в 80% случаев. Сейчас соотношение(по тем ДТП, которые через нас проходят) из 20/80 сдвинулось в 70/30 - то есть практически перевернулось наоборот. В случае же когда мотоциклист забодал пешехода, в большинстве случаев виноват именно мот и это создает очень нефиговую моральную проблему для выезжающих.

**Comment by elagin** [comment]
Спасибо за информацию, но я так и не понял как редкость события влияет на формирование строки :)

**Comment by rjhdby** [comment]
Визуальное выделение нестандартной ситуации.
Юридически это ДТП, но фактически, в контексте МГ,событие требующее отдельного подхода.
