### ISSUE TITLE
Исключение при отправке "отбой".

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#321]

**Comment by elagin** [comment]
Инцидент на сервере правильно меняет статус.

**Comment by rjhdby** [comment]
не понял

**Comment by elagin** [comment]
Выбираю "отбой", приложение падает, но при обновлении инцидент менят нужный статус. Дальше ошибку не копал, поэтому ни чего не написал.

**Comment by elagin** [comment]
Ошибка из-за очередной попытки вторичного потока работать с гуем. Исправлено https://github.com/rjhdby/motocitizen/pull/326.
Присутствует костыль, т.к. пока не придумал как передовать новый статус. Предположительно это должен возвращать сервер.
