### ISSUE TITLE
UI Замена шестеренки

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#33]
Обычно шестеренка это доступ к настройкам. У нас же это меню. Думаю, что стоит либо оставить шестеренку, но сделать чтобы под ней настройки открывались, либо заменить на три горизонтальные линии либо три вертикальные точки, как это сделано в UI на планшетах.

**Comment by rjhdby** [comment]
Сам рисовал, уж извините. :)
Не возражаю против замены на что-то другое.

**Comment by elagin** [comment]
Насколько нужна вообще эта иконка нужна? В UI телефонов (а как я понял приложение только на телефон и ставиться) ни когда не бывает такого элемента, т.к. меню открывается хардварной кнопкой.

**Comment by rjhdby** [comment]
На будущее, для единообразия дизайна с iOS.
Но в целом принципиальных возражений против ее убирания у меня нет.

**Comment by elagin** [comment]
А iOS-то тут причем? У них UI отвратительный был всегда.

**Comment by rjhdby** [comment]
Под iOS тоже надо будет делать в будущем - многие просят. А там хардварной кнопки нет.

**Comment by elagin** [comment]
Я про то, что дизайн для андроид версии не надо с iOS сдирать.

**Comment by rjhdby** [comment]
Видимо мы не поняли друг друга. Эту шестеренку я разместил с одной целью, чтоб потом, когда будет разрабатываться версия под iOS, не надо было искать замену хардварной кнопке.

**Comment by elagin** [comment]
Да, так и получилось :)

**Comment by elagin** [comment]
Ее больше нет с нами.
