### ISSUE TITLE
Иногда при нажатии на пуш/инцидент в списке открывается другой(старый?) инцедент

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#350]

**Comment by rjhdby** [comment]
В пуше не хватало поля "created", из-за чего он не парсился как инцидент.
Поправил на серверной стороне. Будем проверять.

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/issues/356

**Comment by elagin** [comment]
По-прежнему актуально.
