### ISSUE TITLE
При отправке инцидента не чистится форма его создания и при создании второго все поля уже будут заполнены

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#353]

**Comment by elagin** [comment]
Это как-то странно, активити же заново создается?

**Comment by rjhdby** [comment]
А там не onResume случается?

**Comment by elagin** [comment]
```
    private class CreateAccidentCallback implements AsyncTaskCompleteListener {
        @Override
        public void onTaskComplete(JSONObject result) {
            if (result.has("error")) {
                try {
                    Toast.makeText(context, result.getString("error"), Toast.LENGTH_LONG).show();
                } catch (JSONException e) {
                    Toast.makeText(context, "Неизвестная ошибка" + result.toString(), Toast.LENGTH_LONG).show();
                    e.printStackTrace();
                }
            } else {
                finish();
            }
            enableConfirm();
        }
    }
```

При "отмена" тоже finish();

**Comment by rjhdby** [comment]
А при кнопке back?

**Comment by elagin** [comment]
Причем тут back? Судя по описанию **после** отправки инцидента данные остаются при повторном открытии активити.

**Comment by rjhdby** [comment]
Лучше зайца попытать, с его слов писал

**Comment by elagin** [comment]
Я так и не понял. Вроде переодически сервер ответ не дает, хотя инцидент уже создался. Это по-прежнему воспроизводится?

**Comment by elagin** [comment]
А как кнопку back отловить? Пока идет передача данных можно кнопку эту нажать и наблюдаем недоотправленный инцидент с серой кнопкой "готово".

Брекпоинт в начале onKeyUp при этом не срабатывает.

Естественно enableConfirm() не вызывается и инцидент можно только заново создать.

**Comment by rjhdby** [comment]
вроде давно починили уже
