### ISSUE TITLE
Выводить расстояние до инцидента в пуше.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#354]
Будет проще понять надо ли в приложение переходить.

**Comment by elagin** [comment]
Хотя, вероятно, это серверная задача?

**Comment by rjhdby** [comment]
Клиентская. откуда сервер знает текущие координаты клиента?

**Comment by elagin** [comment]
Просто я так и не разобрался как пуши в список вставляются.

**Comment by rjhdby** [comment]
Основной класс NewAccidentReceived

**Comment by elagin** [comment]
Решено https://github.com/rjhdby/motocitizen/pull/370

**Comment by elagin** [comment]
Пардон, отдыхать надо.
