### ISSUE TITLE
Косяки с парсингом ответа от сервера

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#361]

**Comment by elagin** [comment]
Ни чего не понял. Где описание бага-то? Когда я в лесу инцидент создавал, видел ответ в toast-е. с идентификатором события. Но активити не закрывалось.

**Comment by rjhdby** [comment]
В этом и был баг. Неправильно парсился ответ и приклад считал, что случилась ошибка

**Comment by elagin** [comment]
Был, в смысле сейчас он исправлен?
