### ISSUE TITLE
Долгий запуск приложения

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#37]
Приложение долго загружается (сервый экран).
Надо разобраться с алгоритмом запуска, что-то перенести ближе к концу, чтобы Activity раньше нарисовалось, а потом уже запросы отправлялись.

**Comment by rjhdby** [comment]
Подозреваю, что вынос запроса инцидентов в асинхронный режим должен решить проблему.

**Comment by elagin** [comment]
Погоняй пока мой последний коммит: https://github.com/elagin/motocitizen/tree/async_request
Пока не очень помогает. Там еще авторизация и т.д.

**Comment by elagin** [comment]
Связь по wifi:

onCreate: create map: 1935. Total time : 2748
Startup: End OnResume total time is: 3293
MCAccidents: refreshPoints time is: 4060. Total time : 10896

onCreate: create map: 2056. Total time : 3355
Startup: End OnResume Total time: 3920
MCAccidents: refreshPoints time is: 3823. Total time: 10756

onCreate: create map: 1489. Total time : 2123
Startup: End OnResume Total time: 2480
MCAccidents: refreshPoints time is: 3353. Total time: 9773
Дровишки отсюда: https://github.com/elagin/motocitizen/tree/log

**Comment by elagin** [comment]
Из дома: 
onCreate: create map: 1617. Total time : 2269
Startup: End OnResume Total time: 2636
MCAccidents: refreshPoints time is: 3250. Total time: 9187

**Comment by rjhdby** [comment]
Наверное имеет смысл createMap пихнуть асинхронно

**Comment by elagin** [comment]
Не получиться, т.к. не может вторичный поток с ГУЙней работать. Надо другой код во вторичном потоке выполнять пока карта создается. А м.б. карту вообще создавать перый раз когда на нее переход будет. Таким образом съэкономим время старта.

**Comment by rjhdby** [comment]
> Не получиться, т.к. не может вторичный поток с ГУЙней работать.
Значит не надо с гуйнёй работать.
Точнее надо, но строго при необходимости ее отрисовки.

**Comment by elagin** [comment]
бОльшее время при создании карты занимает как не странно
Inflate.set(context, R.id.map_container, R.layout.google_maps_view);

**Comment by rjhdby** [comment]
Создание карт. Может их а асинхрон? Или on demand?

**Comment by elagin** [comment]
on demand
