### ISSUE TITLE
Маркировка инцидентов с motocitizen

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#373]
М.б. их как-то, например, красной рамкой обводить. А то там то дубликаты, то кривые координаты, то еще что-нибудь.

**Comment by rjhdby** [comment]
Конечному пользователю оно однояйственно, откуда пришло. 90% вообще не в курсах наших политических игрищ

**Comment by elagin** [comment]
Я о том, что от-туда часто некорректная информация проходит.

**Comment by rjhdby** [comment]
Ну приходит.
Даже если мы их как-то пометим, информация достоверней не станет. А вот вопросы "а чо это оно выделено?" появятся.

**Comment by elagin** [comment]
Зато сразу можно понять, что ее достоверность под сомнением. М.б. на голосование вынести?

**Comment by rjhdby** [comment]
Автоматом их больше не получаем
