### ISSUE TITLE
Мой инцидент.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#38]
Вероятно стоит как-то выделить созданный самим пользователем инцидент: цветом, или расположением вверху списка или как-то еще.

**Comment by rjhdby** [comment]
Выделяется красной плашкой справа.

**Comment by elagin** [comment]
И те в которые я сообщения писал или выехал?

**Comment by rjhdby** [comment]
Те, в которых как то засветился.

В принципе конечно можно отдельно выделись созданные, но при реальной эксплуатации это крайне редкое событие, можно даже сказать уникальное.

**Comment by elagin** [comment]
Тогда хотя бы сортировка не помешала таких. Пусть редко, но лишним не будет.
