### ISSUE TITLE
Завести локальную БД под хрвнение истории прочитанных сообщений. Ну и для прочего на будущее

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#380]

**Comment by elagin** [comment]
Хранение истриии и без БД хорошо получилось.

**Comment by rjhdby** [comment]
Я его уже запорол.
Ну и в целом, такое лучше в БД хранить, а не в преференсах - они для другого несколько.

**Comment by elagin** [comment]
Разве не в файле хранили? Там как раз было удобно, когда не было сообщений список сам себя удалял.

**Comment by rjhdby** [comment]
Посмотри коммит. Там с БД все очень красиво получается.

PS Снял нафиг галку "rearrange code", а то меняешь одну строку, а он распидорашивает весь класс сверху донизу.
