### ISSUE TITLE
AndroidManifest.xml

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#384]
Ни фига не могу понять, почему у нас AndroidManifest.xml в разных местах должен лежать. Где он в проекте пропичывается? Давай уже пофиксим один раз.
Давай его внутрь переложим и от одной из папок "motocitizen" откажемся.

**Comment by elagin** [comment]
В build.gradle он указан без подпапок выше или ниже, значит рядом и должен лежать?

**Comment by rjhdby** [comment]
Я так и не понял. У меня на работе он внутри ищет, а дома - снаружи.

**Comment by elagin** [comment]
Сделай git clone в новую папку - не будет собираться. Значит надо переделать и закоммитить.
