### ISSUE TITLE
Лишние запросы при работе с инцидентом.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#41]
Например после нажатия "выехал". Вызывается mcaccidents / getlist в котром возвращется измененный инцидент. Думаю, что это лишнее. Применилось ли это изменение можно понять по позвращаемому результату отправки "выехал".
А если кто-то за это время тоже изменил инциден то должен придти пуш.

**Comment by elagin** [comment]
Или в ответ на "выехал" сразу отдается обновленный инцидент.

**Comment by rjhdby** [comment]
в ответ на выехал вызывается обновление списка

**Comment by elagin** [comment]
Да. Зачем?

**Comment by rjhdby** [comment]
хз

**Comment by rjhdby** [comment]
Думаю стоит оставить. Лишнее обновление никогда не лишнее.
