### ISSUE TITLE
Отображение кнопок "список" и "карта".

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#411]
Мне кажется то, что сейчас активно должно быть серым, а то, что можно нажать белым.

**Comment by rjhdby** [comment]
Ну обычно наоборот, то , что активно выделяется.

**Comment by elagin** [comment]
А на вид получается, что кнопка не активная. Например у активного таба фон другой. Эти кнопка практичкски табы.

**Comment by rjhdby** [comment]
Небольшой нюанс. Он не серый, а alpha=0.5 :)
Можно поменьше альфу сделать, но не наоборот. Общечеловеческий принцип обычно такой, что чем ярче - тем активнее.

**Comment by elagin** [comment]
Что значит "активнее" ? Если кнопка серая, это всю дорогу означало, что эта кнопка не сработает при нажатии. Поэтому она и серая.

**Comment by rjhdby** [comment]
http://www.google.com/design/spec/layout/adaptive-ui.html#adaptive-ui-patterns
Раздел Transform, там пример работы с табами

**Comment by elagin** [comment]
Не вижу в приложении жирной черты, которая показывает какой из табов активный.

**Comment by rjhdby** [comment]
Вот же ж докопался :)
В любом случае серым должно быть то, что можно нажать, а ярким то, что нажато. Хоть тут я прав. :P

**Comment by elagin** [comment]
Да, тут ты прав. Просто все время элементы которые нельзя использовать были серыми, а потом в гугл наняли наркоманов, которые сделали в гайдлайнах наоборот.
