### ISSUE TITLE
MyApp - все статичные методы.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#412]
А это ты зачем сделал? Уходили от статиков и обратно к ним пришли?

**Comment by rjhdby** [comment]
MyApp - это корневой процесс. Своеобразный main(), а он всегда статик.
Application всегда создается раньше всех активити и служит как раз для хранения и управления общими данными/статусами для всего приложения.

**Comment by elagin** [comment]
С чего ты взял, что там должно все статиком быть? Оно и без статика неплохо работало. Половина объектов вообще создавалось по требованию.

**Comment by rjhdby** [comment]
Подход был неверный. По факту при старте приложения создавался MyApp(так как он был Application прописанный в манифесте), а потом из активити создавался еще один инстанс MyApp.
http://www.vogella.com/tutorials/AndroidLifeCycle/article.html

Application - это корень приложения, практически как в C функция main(). дефолтный Application создается и запускается первым, даже если его явно не создавать в коде.

**Comment by elagin** [comment]
Причем тут сам Application? Я тебе говорю о том, что когда я сделал так, что все объекты хранящиеся в MyApp создавались по требованию заметно уменьшилось время старт приложения.

**Comment by rjhdby** [comment]
Ну так MyApp у тебя был extend Application.
Если посмотришь внимательнее, то я всего лишь перенес создание базовых объектов из Activity в Application. Соответственно на скорости отрицательно сказаться не должно вообще никак.
