### ISSUE TITLE
Унификация ответов сервера

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#413]
Все ответы сервера должны иметь одинаковый формат.

Начал переделывать запросы на IntentService. Поэтому определение есть ли ошибка в ответе будет производиться в его методе.
Сейчас приходится писать:

```
    public static boolean isError(String action, JSONObject response) {
        switch (action) {
            case MyIntentService.ACTION_AUTH:
                return !response.has("id");
        }
....
```

**Comment by elagin** [comment]
Пардон, перенесено https://github.com/rjhdby/MotoTimes.motobat.server/issues/15

**Comment by rjhdby** [comment]
Новое API в разработке
