### ISSUE TITLE
Не собирается проект: MyLocationManager

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#416]
/home/elagin/dev/android/Motocitizen/Motocitizen/src/motocitizen/draw/Rows.java
Error:(101, 59) error: cannot find symbol variable volunteer_row
/home/elagin/dev/android/Motocitizen/Motocitizen/src/motocitizen/draw/VolunteerRow.java
Error:(15, 54) error: cannot find symbol variable volunteer_row
/home/elagin/dev/android/Motocitizen/Motocitizen/src/motocitizen/geolocation/MyLocationManager.java
Error:(21, 19) error: cannot find symbol class SecuredLocationManagerInterface
Error:(18, 24) error: cannot find symbol class SecuredLocationManagerInterface
Error:(25, 40) error: cannot find symbol class FakeLocationManager
Error:(28, 40) error: cannot find symbol class NormalLocationManager
Error:(35, 56) error: cannot find symbol class NormalLocationManager
Error:(36, 36) error: cannot find symbol class FakeLocationManager

**Comment by rjhdby** [comment]
забыл в git добавить, вечером дозалью коммит

**Comment by elagin** [comment]
Спасибо.
