### ISSUE TITLE
Контроль вводимых значений в радиусе оповещения

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#44]
Длина экватора земли 40.075км. Имеет смысл подумать над ограничением на ввод дистанции. 20.038км на планете земля достаточно :)

**Comment by elagin** [comment]
А где у нас ручной ввод дистанции?

**Comment by rjhdby** [comment]
В настройках вводишь дистанцию, на которой хочешь получать оповещения

**Comment by rjhdby** [comment]
1292e6736f01dd350617fb8cb4168df9b35e77b0
