### ISSUE TITLE
Игнорировать инцидент.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#47]
Может быть стоить когда-нибудь сделать возможность игнорировать изменения по инциденту. Отображать его серым цветом, пуши на него не приходят и из "getlist" он тоже исключен.

**Comment by rjhdby** [comment]
А вот права модератора то я тебе выдать забыл. Там есть функционал "скрыть", при котором инцидент помечается серым и обычным пользователям не виден.
