### ISSUE TITLE
После первой авторизации не убралась клавиатура

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#49]
Ввел логин/пароль, нажал войти. Вошло, отрисовало главный экран, но клавиатура не скрылась.

**Comment by elagin** [comment]
Я пока это активити переделывал много раз его по всякому использовал не разу такого не было, да и странно вообщеЮ активи-то разные, вроде не может при переходе клавиатура оставаться. Да и поля для ввода нет в Startup чтобы клавиатура опять выскочила.
Правда я не пробал приложение переустанавливать, м.б. в отладочной версии дело.
