### ISSUE TITLE
Вынести не листенеры из MCListeners

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#56]
наверное стоит вынести parseSendMessageResponse и parseOnwayResponse из MCListener в соответствующие классы

**Comment by elagin** [comment]
Да, они как раз выносятся при вынесении описания инцидента в отдельное активити.

**Comment by elagin** [comment]
Вроде готово: https://github.com/rjhdby/motocitizen/commit/f25700ef5f77a6cad96eacf4ace2a84d9fde053e
