### ISSUE TITLE
Переделать PreferenceActivity в PreferenceFragment

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#58]
У нас минимальный API 12, а PreferenceActivity начиная с 11 является depricated

**Comment by rjhdby** [comment]
Затронет глобально. Придется и основной экран под фрагмент переделывать.

**Comment by elagin** [comment]
Давай пока обождем. По мере вынесения всего из главного окна меньше переделывать нужно будет.

**Comment by rjhdby** [comment]
Да уже почти сделал

**Comment by elagin** [comment]
Посмотрим сколько времени я это мержить буду :)

**Comment by rjhdby** [comment]
У тебя есть воззможность закоммитить раньше и мержить придется мне :)

**Comment by elagin** [comment]
Я как раз подумал, "кто последний, тот дурак" :)
