### ISSUE TITLE
"Для статистики"

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#6]
Сделать возможным создавать событие с флагом "для статистики".
Необходимо продумать функционал.

**Comment by elagin** [comment]
Добавить галку "Для статистики" в экран создания.
Добавить в настройки "Отображать инциденты 'для статистики'", передавать этот флаг при запросе новых событий, чтобы сервер их отгружал только если они нужны.

В будущем может имеет смысл расширить для таких инцидентов настройки (текстовые/звуковые уведомления по расстоянию), но это может усложнить GUI.

**Comment by rjhdby** [comment]
наконец то...
