### ISSUE TITLE
По максимуму отказаться от ссылок к Startup.context в прочих Activity

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#61]

**Comment by rjhdby** [comment]
https://github.com/rjhdby/motocitizen/commit/4792eee2f0422d0d2e0d41626bde55a4bb3124f3

**Comment by elagin** [comment]
Я тоже поковыряюсь.

**Comment by rjhdby** [comment]
cdae8c39b5767a3d29a0e2e349801537139e6ee0

**Comment by rjhdby** [comment]
Очередная порция 392ca81c346a3baf6bcae994e036a5d78f09703d

**Comment by rjhdby** [comment]
1bc1d6df40511c737c51be4e2d0c974938bccb73
