### ISSUE TITLE
Регистрация через приложение.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#68]
Добавить функционал:
В клиенте: кнопку "Регистрация", поле для ввода секретного номера из СМС.
На сервере все остальное.

**Comment by rjhdby** [comment]
Для начала надо определиться на каких серверах будем располагаться. Есть большая вероятность, что с motocitizen придется уйти. Там уже и про регистрацию можно думать.
Вариант с СМС не самый лучший.
1) Они платные
2) Сложности с рассылкой - нужно регистрировать юридическое лицо
3) Провайдеры, готовые обслуживать мелких клиентов(а мы так вообще мизерный будем), обычно имеют постоянные проблемой с доставкой.

**Comment by elagin** [comment]
Создал, чтобы было.
Можно наоборот: чтобы пользователь присылал СМС на указанный номер.

**Comment by rjhdby** [comment]
Думаю уже не актуально
