### ISSUE TITLE
Копия контекстного меню для стандартного (AccidentDetails)

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#69]
Сейчас есть контенстное меню которе вызывается 
1) при долгом нажатии на списке инцидентов 
2) на заголовке в "подробности".
Нужно для второго случая перенести в стандартное. Т.к. контекстное обычно используется когда есть несколько одинаковых объектов.

**Comment by rjhdby** [comment]
Контекстное меню есть и для сообщений

**Comment by rjhdby** [comment]
Актуально?

**Comment by elagin** [comment]
Надо подумать, что что-то уже переносил.
