### ISSUE TITLE
Внедрить функционал понижения роли пользователя до readonly

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#74]

**Comment by elagin** [comment]
Я как раз авторизацию причесал немного...

**Comment by rjhdby** [comment]
Серверная часть готова.
Теперь надо для модераторов в контекстное меню добавить пункт "бан" и в истории добавить тэг "ban"

**Comment by elagin** [comment]
Юзер будет баниться для конкретного инцидента?

**Comment by rjhdby** [comment]
Заноситься в историю будет для инцидента, что бы можно было концы найти.

**Comment by elagin** [comment]
Это не верно. Бан должен храниться в юзере с указанием кем, когда за какой инцидент он был забанен.

Инцидент с баном ни как не соотноситься.

 Искать ты будешь как забанен юзер или нет, в каждый инцидент заглядывать?

**Comment by rjhdby** [comment]
все изменения хранятся в history, по ней и ищется.
В частности для поиска бана конкретного пользователя(id=9) делаем
SELECT * FROM history WHERE id_user=9 AND action='ban';
Модератор в данном случае будет в поле params в виде json
{"moderator":"rjhdby"}  (возможно имеет смысл хранить и id модератора, но это уже для внутренних разборок и на ходовые качества не влияет)

CREATE TABLE IF NOT EXISTS `history` (
  `id` bigint(20) unsigned NOT NULL AUTO_INCREMENT,
  `id_ent` bigint(20) unsigned NOT NULL,
  `id_user` bigint(20) unsigned NOT NULL,
  `action` varchar(255) NOT NULL,
  `timest` timestamp NOT NULL DEFAULT CURRENT_TIMESTAMP,
  `params` varchar(10000) NOT NULL DEFAULT '{}',
  PRIMARY KEY (`id`),
  KEY `id_ent` (`id_ent`),
  KEY `id_user` (`id_user`),
  KEY `action` (`action`)
) ENGINE=InnoDB  DEFAULT CHARSET=utf8 AUTO_INCREMENT=1141 ;

**Comment by elagin** [comment]
history это что, кто куда поехал?

Я тебе о том и говорю, что факт бана надо хранить либо в самом юзере. Все равно при авторизации ты его находишь. Таблица по юзерам явно меньше history.

А еще лучше завести еще одну таблицу для банов. Там, например, хранить:
* факт бана
* id забаненого
* id забаневшего
* дату бана
* можно дату автоматического разбана (null - бессрочно). Если дата разбана прошла, то при авторизации заодно и разбанить.
* id инцидента
* комментарий от забаневшего.

Все равно размер этой таблицы будет меньше истории,

**Comment by rjhdby** [comment]
В юзере хранится его текущая роль. В случае бана это будет readonly.
Ну и таблица юзеров не может хранить историю модераторских действий по нему

Можно завести отдельную таблицу по модераторским действиям, надо только понять ее целесообразность. Тут не такие объемы данных, что бы париться по быстродействию. По моим прогнозам максимум 20.000 записей в history в год.

Тут еще не стоит забывать контекст использования. Применение бана оправдано в двух случаях:
1) Пользователь создает инциденты не соответствующие целям приложения(спам/реклама/ложные сообщения)
2) Пользователь неадекватен в комментариях - мат, угрозы, троллинг и т.д.
В обоих этих случаях бан перманентен(тут мы делаем суровые осуждающие лица)

В случае если пользователь забанен по ошибке/по беспределу - редкое и индивидуальное явление, которое в любом случае выносится на обсуждение админам/модераторам и там уж или подтверждается справедливость или модератор лишается погон.

PS Но на будущее давай запланируем доработку схемы БД, я не против. Дядьку из РИА-Новостей еще подтянем.

**Comment by elagin** [comment]
Почему в случае бана роль readonly? Что-то одно нельзя оставить?

Отдельная таблица по модераторским действиям должна быть из-за того, что это отдельная сущность и сколько записей в history не важно.

**Comment by rjhdby** [comment]
**Почему в случае бана роль readonly? Что-то одно нельзя оставить?**
В смысле?

**Comment by elagin** [comment]
Почему в случае бана роль **ридноли** а не **бан**? Для чего нужны два понятия?

**Comment by rjhdby** [comment]
Это одно понятие. Бан - это действие модератора, которое является понижением роли до readonly. Если мы сделаем кнопку "понизить роль до readonly" - во-первых распидорасит меню, во-вторых народ не поймет.
Забудь про такое понятие как "бан" - оно просто замена длинного определения для краткости.

**Comment by rjhdby** [comment]
743ac1a93a209f0152381bb4ff946892ebb4f3b1
