### ISSUE TITLE
Автризация и роли.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#77]
Мне кажется что нужно что-то объеденить.
Как минимум "Анонимный" пользователь это где-то рядом с ролю "readonly".
Где-то для проверки авторизации используется поле mc.name, где-то mc.anonim.
Предлагаю вместо поля mc.anonim использовать роль readonly.

С mc.name и mc.login тоже как-то запутано. Первое это имя пользователя в системе, второе то, что он написал в окне авторизации. Добавляет радости что у нас регистронезависимая авторизация.
Было бы правильно хранить mc.login в PreferenceManager (и использовать только для входа в систему), а mc.name в MCAuth.

**Comment by elagin** [comment]
А вообще mc.name заменить на "я"

**Comment by rjhdby** [comment]
Readonly это не только анонимный, но еще и забаненый

Отдельный anonim тем хорош, что не надо делать проверок на авторизацию, а для readonly авторизация все же нужна.

Про name и login - изначально идея была в том, что они разные могут быть, но сейчас по факту разницы нет, можно резать.

**Comment by elagin** [comment]
А чем забаненный от ридонли отличается? Одного можно разбанить, а другого нельзя разридонлить?

Аноним и любая роль это все равно права доступа, зачем две сущности одного и того же уровня?

**Comment by rjhdby** [comment]
Потому что они качественно отличаются.
У пользователя может быть два состояния: авторизованный/не авторизованный
А дальше уже идет градация по правам

**Comment by elagin** [comment]
Тогда неавторизованный это **роль** "anonim ",

**Comment by rjhdby** [comment]
Роль - это свойство применимое к конкретному пользователю.
Аноним же - это не один пользователь, а совокупность всех неавторизованных(гостевой вход).
Это принципиально разные понятия.

Ну и кроме того, получение роли у нас завязано на сервер. То есть с переносом функциональности в роли мы в нагрузку получаем необходимость запроса авторизации, создание механизма распознавания гостевой это вход или просто в пароле ошибся, возможно еще где вылезет.

**Comment by elagin** [comment]
Просто аноним это роль по-умолчанию. Пока юзер не авторизовался. Да и существует только в клиентской части.

**Comment by elagin** [comment]
Залогонился - повысилась роль до нужной. Разлогинился - упала до анонимной.

**Comment by rjhdby** [comment]
Ну и чем оно тогда отличается от существующего порядка вещей?

**Comment by elagin** [comment]
Тем что находиться отдельно от ролей и проверять приходится специальным образом.
