### ISSUE TITLE
Контроль создания события. Выдавать предупреждение, если не создалось.

### ISSUE THREAD

**Issue by rjhdby** [rjhdby/motocitizen#8]

**Comment by elagin** [comment]
В первом приближении решено здесь https://github.com/elagin/motocitizen/tree/no_network но пулл-реквест пока не сделал.

P.S. Надо стараться инцидент называть инцидентом, событием может быть например пришедшее обновление инцидента.

**Comment by elagin** [comment]
Если вопрос решен, то м.б. стоит закрыть это обсуждение?
