### ISSUE TITLE
Дата написания сообщения

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#80]
Почему её нет?

**Comment by rjhdby** [comment]
дабы не загромождать. Время жизни инцидента(в интерфейсе) 24часа, очередность ответов соблюдается, имхо дата/время лишнее.
Можно пользователей попытать, надо ли оно им.

**Comment by elagin** [comment]
Не так уж много места время-то занимает, но можно понять насколько давно написано какое сообщение.

**Comment by rjhdby** [comment]
5ee32e600d5716000164516d6bd358e01acdf5e4
