### ISSUE TITLE
Хранение дат

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#81]
Обратил внимание, что в вики в разных местах по-разному дата используется. Лучше всего использовать unixtimestamp, который в java нативный. Глазами отлаживать не удобно зато нет проблем с таймзоной.

**Comment by rjhdby** [comment]
Формат везде одинаковый, как mysql стандартно timestamp отдает.
Можно на unixtime поменять, но придется придумать как избежать распидорашивания на момент когда сервер начнет отдавать unixtime, а пользователи еще не обновят клиента(или наоборот)

**Comment by elagin** [comment]
Да ни как, будет у них кривая дата или исключения пока не обновятся :) Пока юзеров мало. Ну поплачит заяц немного...

**Comment by rjhdby** [comment]
Давай так сделаем.
Добавлю во все методы, где есть дата, поле unixtime с сохранением полей со старым форматом.
По окончанию доработки напишу сюда.

**Comment by rjhdby** [comment]
В списке инцидентов, волонтеров, истории и сообщений добавил поле uxtime.

**Comment by elagin** [comment]
Поддержу сейчас в вообщениях.

**Comment by elagin** [comment]
Для создания инцидентов ты сделал?

**Comment by rjhdby** [comment]
Сервер все в unixtime отдает.
Но пока не принимает

**Comment by rjhdby** [comment]
https://github.com/rjhdby/MobileServer/issues/9
