### ISSUE TITLE
Отображение географических координат в инциденте.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#82]
В городе есть адрес, но за МКАД геокодирование не всегда работает.
Предлагаю придумать как опционально отображать координаты

**Comment by rjhdby** [comment]
А зачем? Ссылка на карту есть, а координаты сами по себе вещь достаточно бессмысленная.
Или ты что-то другое имел в виду?

**Comment by elagin** [comment]
Вот пример, поехал эндурист в глубокий лес и там мот в болоте утопил. Запустил приложение, создал инцидент. Адрес: МО, д. Миндюкино. А сама точка где-то далеко в лесу. Я вбил бы координаты в навигатор и поехал к нему.

А сейчас я буду зумировать карту только до такого масштаба, чтобы хоть что-то кроме большого пятна леса было на карте, чтобы как-то привязаться. Но этого может быть не достаточно в большом лесу или карта у меня не очень подробная. Или дорожек на карте там нет (у нас кстати векторные карты только поддерживаются, а они значительно менее подробные). Так вот, приеду я в лес и буду там орать и искать этого гражданина. А по координатам я его найду с точностью в 10 м.

**Comment by rjhdby** [comment]
Ок.
Первое, что приходит в голову - включить в контекстное меню пункта "открыть в навигаторе" и там интентом бросать куда хочется
Второе - выводить координаты в балуне на карте

**Comment by elagin** [comment]
Точно! В дельтовском приложении открывается навигационное приложение.

**Comment by elagin** [comment]
Не уверен что в контекстом меню. М б. достаточно в меню инцидента?
Туда же пункт "координаты". Мало ли, в телефоне нет навигатора, а отдельный девайс есть.

**Comment by rjhdby** [comment]
В принципе у меня только одна просьба, что бы они показывались по запросу, а не всем и всегда. Остальное - как считаешь нужным.

**Comment by elagin** [comment]
Согласен

**Comment by rjhdby** [comment]
61e228384dc882287cc3164b8045bcab4eafc565
