### ISSUE TITLE
android.app.Activity.onCreateView - Error inflating class fragment

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#83]
По мотивам https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.IllegalArgumentException&tf=Activity.java&tc=android.app.Activity&tm=onCreateView&nid&an&c&s=new_status_desc

**Comment by elagin** [comment]
Попробуем решение: http://stackoverflow.com/questions/19874882/android-view-inflateexception-binary-xml-file-error-inflating-class-fragment

**Comment by rjhdby** [comment]
Закрыто?

**Comment by elagin** [comment]
Вроде пока не воспроизводиться.
