### ISSUE TITLE
Длинное сообщение - кривая таблица.

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#89]
![screenshot_2015-04-09-14-34-30](https://cloud.githubusercontent.com/assets/611744/7065953/047bb4c2-dec6-11e4-8095-312f9105fe82.png)

**Comment by rjhdby** [comment]
уже поправил

**Comment by elagin** [comment]
Вероятно это здесь: https://github.com/rjhdby/motocitizen/commit/5ee32e600d5716000164516d6bd358e01acdf5e4
Не забывай, плз. давать ссылку на коммит.

**Comment by rjhdby** [comment]
нет, еще не заливал. У меня проблема с заливкой - не могу часто.

**Comment by elagin** [comment]
Давай вечером соберешь. Много чего сегодя сделаем.
