### ISSUE TITLE
An error occured while executing doInBackground() 

### ISSUE THREAD

**Issue by elagin** [rjhdby/motocitizen#92]
Источник: https://play.google.com/apps/publish/?hl=ru&dev_acc=07887830268054869254#ErrorClusterDetailsPlace:p=motocitizen.main&et=CRASH&lr=LAST_7_DAYS&ecn=java.lang.RuntimeException&tf=Handler.java&tc=android.os.Handler&tm=%253Cinit%253E&nid&an&c&s=new_status_desc

**Comment by rjhdby** [comment]
закрывай
